import "../../app/globals.css";
import { Inter } from "next/font/google";
import Sidebar from "./Sidebar";
import "./style.css";
import Navbar from "./Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "campusStockHub | IMS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          background:
            "linear-gradient(153.47deg, rgba(255, 255, 255, 0) -341.94%, #14101d 95.11%);",
        }}
      >
        <Navbar />
        <div style={{display:"flex"}}>
        <Sidebar />
        {children}
        </div>
      </body>
    </html>
  );
}
